export interface GistResult {
  gistId: string;
  gistUrl: string;
  colabUrl: string;
}

/**
 * Upload a .ipynb file to GitHub Gist (public, unauthenticated).
 * Returns the gist ID, raw gist URL, and the Google Colab open URL.
 *
 * Falls back gracefully: if the upload fails, returns null instead of throwing.
 */
export async function uploadToGist(
  notebookJson: string,
  filename: string
): Promise<GistResult | null> {
  try {
    const response = await fetch('https://api.github.com/gists', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'Paper2Colab/1.0',
      },
      body: JSON.stringify({
        description: 'Generated by Paper2Colab — research paper tutorial notebook',
        public: true,
        files: {
          [filename]: {
            content: notebookJson,
          },
        },
      }),
    });

    if (!response.ok) {
      console.warn(`[gist] Upload failed: ${response.status} ${response.statusText}`);
      return null;
    }

    const data = (await response.json()) as { id: string; html_url: string };
    const gistId = data.id;
    const gistUrl = data.html_url;
    // Google Colab can open notebooks from a gist URL
    const colabUrl = `https://colab.research.google.com/gist/${gistId}/${encodeURIComponent(filename)}`;

    return { gistId, gistUrl, colabUrl };
  } catch (err) {
    console.warn('[gist] Upload error (non-fatal):', err);
    return null;
  }
}
